# Generated by Django 2.2.9 on 2019-12-20 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhostPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghostTitle', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=280)),
                ('is_boast', models.BooleanField(default=False)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('goodvote', models.IntegerField(default=0)),
                ('badvote', models.IntegerField(default=0)),
                ('totalvotes', models.IntegerField(default=0)),
            ],
        ),
    ]
